#============== OS LAYER ==================
FROM base-image
#==========================================
# METADATA OF THE IMAGE
LABEL description "mgx image based on base image" version="1.0" maintainer="Meshing team <lihpccg@gmail.com>"
#==========================================
SHELL ["/bin/bash", "-c"]
#==========================================
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#==========================================
RUN source /spack/share/spack/setup-env.sh &&\
    spack env activate meshing-env &&\
    spack add mgx~smooth3d^vtk-maillage~opengl2+qt &&\
    spack install --no-checksum &&\
    rm -rf /spack/var/spack/cache/*
#==========================================
