name: Reusable Cmake workflow 

on:
  workflow_call:
    inputs:
      run-tests:
        required: true
        type: boolean

env:
  QT_QPA_PLATFORM: offscreen

jobs:
  main:
    name: CMake build & run
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Linux, Windows or Mac.
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lihpc-computational-geometry/cmake-cgcore-mgx:latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout source code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # seems to be needed by codecov
          submodules: recursive

      - name: Build with Cmake
        shell: bash
        run: |
          cmake -S . -B build --preset=ci --install-prefix=/${{ github.event.repository.name }}-install
          cmake --build build --target install

      - name: Run unit tests
        if: ${{ inputs.run-tests }}
        shell: bash
        run: |
          cmake --build build --target test

      - name: Archive unit tests logs
        if: ${{ inputs.run-tests }} && failure()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-logs
          path: /__w/tkutil/tkutil/build/Testing/Temporary/LastTest.log

      - name: Test C++ lib install
        shell: bash
        run: |
          cd test_link/
          cp ../CMakePresets.json .
          # Do not use ${{ github.event.repository.name }}_ROOT variable: package names != project names (sometimes)
          cmake -S . -B build --preset=ci -DCMAKE_PREFIX_PATH=/${{ github.event.repository.name }}-install
          cmake --build build
          cd build
          ctest
