name: 'Image Creator'

on:
  workflow_dispatch:
    inputs:
      mgx:
        description: 'Builg mgx image'
        required: true
        type: boolean
      gmds:
        description: 'Build gmds image'
        required: true
        type: boolean

env:
  REGISTRY: 'ghcr.io'
  USER_NAME: 'lihpc'
  DOCKERFILE_PATH: './images'
  if: ${{ inputs.mgx }}
    PRODUCT_NAME: 'mgx'
  if: ${{ inputs.gmds }}
    PRODUCT_NAME: 'gmds'

jobs:
  build-and-push:
    name: U22.04-S0.19-mgx
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USER_NAME }}/${{ env.PRODUCT_NAME }}
          labels: |
            org.opencontainers.image.title=lihpccg
            org.opencontainers.image.description=Image to build/install/run ${{ env.PRODUCT_NAME }}
            org.opencontainers.image.vendor=CEA
          tags: |
            type=raw, ${{ env.PRODUCT_NAME }}_latest
            type=raw, ${{ env.PRODUCT_NAME }}_{{date 'YYYYMMDD'}}

      - name: Build and push Docker image for mgx
        uses: docker/build-push-action@v3
        with:
            file: ${{ env.DOCKERFILE_PATH }}/Dockerfile_${{ env.PRODUCT_NAME }}
            push: true

