name: 'Image Creator'

on:
  workflow_dispatch:
    inputs:
      mgx:
        description: 'Builg mgx image'
        required: true
        type: boolean
      gmds:
        description: 'Build gmds image'
        required: true
        type: boolean

env:
  REGISTRY: 'ghcr.io'
  USER_NAME: 'lihpc'
  DOCKERFILE_PATH: './images'

jobs:
  build-and-push:
    name: U22.04-S0.19-mgx
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for mgx
        if: ${{ inputs.mgx }}
        uses: docker/build-push-action@v3
        with:
            file: ${{ env.DOCKERFILE_PATH }}/Dockerfile_mgx
            push: true

      - name: Build and push Docker image for gmds
        if: ${{ inputs.gmds }}
        uses: docker/build-push-action@v3
        with:
            file: ${{ env.DOCKERFILE_PATH }}/Dockerfile_gmds
            push: true
